import {chromium,webkit,devices} from '@playwright/test';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {PNG} from 'pngjs';
await fs.mkdir('evidence',{recursive:true});
const result={tests:[],engines:[],errors:[],createdAt:new Date().toISOString(),scope:'Real browser functional and rendered-output checks. Includes a complete hands-free journey on desktop, Chromium touch emulation and WebKit. Not physical-device or reference-fidelity certification.'};
const url=process.env.LAB_URL||'http://127.0.0.1:4173/';
for(const [name,engine,options] of [['desktop',chromium,{viewport:{width:1440,height:1000},deviceScaleFactor:1}],['mobile',chromium,{...devices['Pixel 7'],viewport:{width:390,height:844},deviceScaleFactor:1}],['webkit',webkit,{...devices['iPhone 13'],viewport:{width:390,height:844},deviceScaleFactor:1}]]){
 const browser=await engine.launch(engine===chromium?{args:['--use-angle=swiftshader','--enable-webgl','--enable-unsafe-swiftshader']}:{});
 const context=await browser.newContext({...options,recordVideo:{dir:`evidence/${name}-video`,size:options.viewport},reducedMotion:'no-preference'}),page=await context.newPage();page.setDefaultTimeout(18000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const test=async(label,fn)=>{try{await fn();result.tests.push({engine:name,label,status:'passed'});console.log('PASS',name,label);}catch(e){result.tests.push({engine:name,label,status:'failed',error:e.message});console.log('FAIL',name,label,e.message);}};
 const shot=async(label,locator)=>{await (locator||page).screenshot({path:`evidence/${name}-${label}.png`,timeout:30000});};
 const ready=async(id)=>page.waitForFunction(id=>document.querySelector(id)?.dataset.ready==='true',id,{timeout:30000});
 const read=()=>page.evaluate(()=>({...window.__journeyPlayer,y:scrollY,renderProgress:window.__motionLab.progress}));
 const pause=async()=>{if(!(await page.locator('body').evaluate(e=>e.classList.contains('motion-paused'))))await page.locator('#pause').click();};
 const seek=async(p)=>{await page.evaluate(p=>{const e=document.querySelector('#journey'),h=document.querySelector('.journey-sticky').offsetHeight;scrollTo({top:e.getBoundingClientRect().top+scrollY+p*(e.offsetHeight-h),behavior:'instant'});},p);await ready('#tunnel-stage');await page.waitForTimeout(350);};
 const start=async()=>{await page.evaluate(()=>{const e=document.querySelector('#journey');scrollTo({top:e.offsetTop-innerHeight*.25,behavior:'instant'});});await ready('#tunnel-stage');await page.waitForFunction(()=>window.__journeyPlayer.mode==='playing',{},{timeout:15000});};
 try{
 await page.goto(url,{waitUntil:'domcontentloaded'});await ready('#hero-stage');await page.waitForTimeout(900);
 await test('Hero still renders real nonuniform WebGL pixels',async()=>{const image=PNG.sync.read(await page.locator('#hero-stage').screenshot());const colors=new Set();for(let i=0;i<image.data.length;i+=480)colors.add(`${image.data[i]},${image.data[i+1]},${image.data[i+2]}`);assert(colors.size>60);await shot('01-hero');});
 await test('Palette still changes',async()=>{const before=await page.evaluate(()=>window.__motionLab.palette);await page.locator('#palette').click();assert.notEqual(await page.evaluate(()=>window.__motionLab.palette),before);});
 await test('Menu still closes and restores content',async()=>{await page.locator('#menu-toggle').click();assert(await page.locator('#menu').evaluate(e=>e.open));await page.keyboard.press('Escape');assert(!(await page.locator('#menu').evaluate(e=>e.open)));assert(!(await page.locator('#content').evaluate(e=>e.inert)));});
 await page.locator('#depth-stage').evaluate(e=>e.scrollIntoView({behavior:'instant',block:'center'}));await ready('#depth-stage');
 await test('Depth and its Back navigation remain functional',async()=>{await page.locator('#depth-stage').click();await page.waitForFunction(()=>document.querySelector('#detail').open);await page.goBack();await page.waitForFunction(()=>!document.querySelector('#detail').open);});
 await test('No slider or percentage is visible or keyboard-operable',async()=>{assert(!(await page.locator('#scrubber').isVisible()));assert(await page.locator('#scrubber').isDisabled());assert(!(await page.locator('#progress').isVisible()));assert.equal(await page.locator('.outro').count(),0);});
 await test('Journey starts automatically as the viewer enters',async()=>{await start();const before=await read();await page.waitForTimeout(1600);const after=await read();assert(after.progress>before.progress+.025);assert(after.renderProgress>before.renderProgress+.02);assert(after.y>before.y+80);await shot('02-autoplay');});
 await test('Pause freezes camera progress and resume continues',async()=>{await page.locator('#journey-toggle').click();await page.waitForTimeout(150);const a=await read();await page.waitForTimeout(900);const b=await read();assert.equal(b.mode,'paused');assert(Math.abs(b.progress-a.progress)<.001);await page.locator('#journey-toggle').click();await page.waitForTimeout(800);assert((await read()).progress>b.progress+.012);});
 await test('Menu suspends autoplay without losing position',async()=>{await page.locator('#menu-toggle').click();await page.waitForTimeout(100);const a=await read();await page.waitForTimeout(700);assert(Math.abs((await read()).progress-a.progress)<.001);await page.keyboard.press('Escape');await page.waitForTimeout(800);assert((await read()).progress>a.progress+.01);});
 await test('Hold-to-slow changes automatic travel speed and releases',async()=>{const r=await page.locator('#slow').boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();const a=await read();await page.waitForTimeout(1100);const b=await read();assert(b.progress>a.progress);assert(b.progress-a.progress<.021);await page.mouse.up();await page.waitForTimeout(1100);const c=await read();assert(c.progress-b.progress>(b.progress-a.progress)*2);});
 await test('Leave exits instead of trapping the viewer',async()=>{await page.locator('#journey-leave').click();await page.waitForTimeout(250);assert.equal((await read()).mode,'idle');assert(await page.locator('#journey').evaluate(e=>e.getBoundingClientRect().top>innerHeight*.65));});
 if(name==='mobile')await test('Finger-style swipe reenters then plays hands-free',async()=>{const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:185,y:720}]});for(let i=1;i<=14;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:185,y:720-i*35}]});await page.waitForTimeout(22);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForFunction(()=>['playing','entering'].includes(window.__journeyPlayer.mode));await page.waitForTimeout(1200);const a=await read();await page.waitForTimeout(1100);assert((await read()).progress>a.progress+.015);await page.locator('#journey-leave').click();});
 await test('Full hands-free run reaches a different full-screen page',async()=>{
  await start();
  // The actual configured duration runs here: no seeking or mocked time.
  const phases=new Set();for(let i=0;i<95;i++){const d=await read();phases.add(await page.evaluate(()=>window.__motionLab.phase));if(d.mode==='arrival')break;await page.waitForTimeout(550);}
  assert.equal((await read()).mode,'arrival');assert.equal(new URL(page.url()).hash,'#arrival');
  await page.waitForFunction(()=>document.querySelector('#journey-veil').hidden);
  for(const phase of ['portal','dark tunnel','fold','light tunnel','glass / emergence'])assert(phases.has(phase),'Missing '+phase);
  assert(await page.locator('#arrival').isVisible());assert(!(await page.locator('#content').isVisible()));assert(await page.locator('#content').evaluate(e=>e.inert));
  assert(await page.evaluate(()=>scrollY===0&&document.documentElement.scrollHeight<=innerHeight+2));
  assert.equal(await page.evaluate(()=>document.activeElement.id),'arrival-title');await shot('03-arrival');
 });
 await test('Destination cannot scroll down into the old website',async()=>{await page.evaluate(()=>scrollTo({top:99999,behavior:'instant'}));await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>scrollY),0);assert(await page.locator('#arrival').isVisible());});
 await test('Browser Back restores paused journey; Forward restores destination',async()=>{await page.goBack();await page.waitForTimeout(700);assert.equal((await read()).mode,'waiting');assert(!(await page.locator('#content').evaluate(e=>e.inert)));const a=await read();await page.waitForTimeout(900);assert(Math.abs((await read()).progress-a.progress)<.001);await page.goForward();await page.waitForTimeout(450);assert(await page.locator('#arrival').isVisible());});
 await test('Replay really restarts and does not duplicate completion',async()=>{await page.locator('#arrival-replay').click();await page.waitForTimeout(500);assert((await read()).progress<.1);assert.equal((await read()).mode,'playing');await page.waitForTimeout(850);assert((await read()).progress>.015);});
 await test('Resize preserves journey progress, without an unexpected restart',async()=>{await pause();await seek(.62);const a=await read();await page.setViewportSize({width:844,height:390});await page.waitForTimeout(700);assert(Math.abs((await read()).progress-a.progress)<.015);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await shot('04-landscape');await page.setViewportSize(options.viewport);await page.waitForTimeout(700);assert(Math.abs((await read()).progress-a.progress)<.015);});
 await test('Reverse traversal restores the earlier scene',async()=>{await seek(.28);assert.equal(await page.evaluate(()=>window.__motionLab.phase),'dark tunnel');await shot('05-reverse');});
 await test('Destination deep link and reload stay on the new page',async()=>{await page.goto(url+'#arrival');await page.waitForFunction(()=>window.__journeyPlayer.mode==='arrival');assert(await page.locator('#arrival').isVisible());await page.reload();await page.waitForFunction(()=>window.__journeyPlayer.mode==='arrival');assert(!(await page.locator('#content').isVisible()));await page.locator('#arrival-home').click();await ready('#hero-stage');assert.equal(new URL(page.url()).hash,'#interaction');assert(await page.locator('#hero-stage').isVisible());});
 await test('No captured application or graphics errors',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(await page.evaluate(()=>window.__motionLab.errors),[]);});
 }catch(e){result.errors.push({engine:name,error:e.message});try{await shot('fatal');}catch{}}
 result.engines.push({name,version:browser.version(),options,consoleErrors:errors});await context.close();await browser.close();
}
const browser=await chromium.launch({args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'}),page=await context.newPage();
try{await page.goto(url);await page.waitForFunction(()=>window.__motionLab);await page.evaluate(()=>document.querySelector('#journey').scrollIntoView({behavior:'instant'}));await page.waitForTimeout(1800);const y=await page.evaluate(()=>scrollY);await page.waitForTimeout(1200);assert.equal(await page.evaluate(()=>scrollY),y);assert.equal(await page.locator('#pause').getAttribute('aria-pressed'),'true');result.tests.push({engine:'reduced-motion',label:'No unsolicited automatic movement with reduced motion enabled',status:'passed'});}catch(e){result.tests.push({engine:'reduced-motion',status:'failed',error:e.message});}
try{await page.goto(url+'?no-webgl');await page.waitForFunction(()=>document.querySelector('#hero-stage').classList.contains('error'));await page.evaluate(()=>document.querySelector('#journey').scrollIntoView({behavior:'instant'}));await page.waitForFunction(()=>!document.querySelector('#journey-skip').hidden);await page.locator('#journey-skip').click();await page.waitForFunction(()=>window.__journeyPlayer.mode==='arrival');result.tests.push({engine:'fallback',label:'Unavailable graphics have a working nonblocking destination exit',status:'passed'});}catch(e){result.tests.push({engine:'fallback',status:'failed',error:e.message});}await browser.close();
result.summary={passed:result.tests.filter(t=>t.status==='passed').length,failed:result.tests.filter(t=>t.status==='failed').length,fatal:result.errors.length};await fs.writeFile('evidence/results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result.summary));if(result.summary.failed||result.summary.fatal)process.exitCode=1;
