import {chromium,webkit,devices} from '@playwright/test';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {PNG} from 'pngjs';
await fs.mkdir('evidence',{recursive:true});
const result={tests:[],engines:[],errors:[],createdAt:new Date().toISOString(),scope:'Functional and rendered-output tests, not a pixel-equivalence certificate. Mobile is browser emulation, not physical hardware.'};
for(const [name,engine,options] of [['desktop',chromium,{viewport:{width:1440,height:1000},deviceScaleFactor:1}],['mobile',chromium,{...devices['Pixel 7'],viewport:{width:390,height:844},deviceScaleFactor:1}],['webkit',webkit,{...devices['iPhone 13'],viewport:{width:390,height:844},deviceScaleFactor:1}]]){
 const browser=await engine.launch(engine===chromium?{args:['--use-angle=swiftshader','--enable-webgl','--enable-unsafe-swiftshader']}:{});
 const context=await browser.newContext({...options,recordVideo:{dir:`evidence/${name}-video`,size:options.viewport},reducedMotion:'no-preference'}),page=await context.newPage();page.setDefaultTimeout(18000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const test=async(label,fn)=>{try{await fn();result.tests.push({engine:name,label,status:'passed'});}catch(e){result.tests.push({engine:name,label,status:'failed',error:e.message});}};
 const shot=async(label,locator)=>{await (locator||page).screenshot({path:`evidence/${name}-${label}.png`,timeout:30000});};
 const ready=async(id)=>page.waitForFunction(id=>document.querySelector(id)?.dataset.ready==='true',id,{timeout:30000});
 const scene=async(p)=>{await page.evaluate(p=>{const e=document.querySelector('#journey'),h=document.querySelector('.journey-sticky').offsetHeight;scrollTo({top:e.getBoundingClientRect().top+scrollY+p*(e.offsetHeight-h),behavior:'instant'});},p);await ready('#tunnel-stage');await page.waitForTimeout(1000);};
 try{
 await page.goto('http://127.0.0.1:4173/',{waitUntil:'domcontentloaded'});await ready('#hero-stage');await page.waitForTimeout(1700);
 await test('Hero renders nonuniform real WebGL pixels',async()=>{const image=PNG.sync.read(await page.locator('#hero-stage').screenshot());const colors=new Set();for(let i=0;i<image.data.length;i+=480)colors.add(`${image.data[i]},${image.data[i+1]},${image.data[i+2]}`);assert(colors.size>60);await shot('01-hero');});
 await test('Palette changes from button activation',async()=>{const before=await page.evaluate(()=>window.__motionLab.palette);await page.locator('#palette').click();assert.notEqual(await page.evaluate(()=>window.__motionLab.palette),before);await page.waitForTimeout(750);await shot('02-palette');});
 await test('Motion pause toggles both ways',async()=>{await page.locator('#pause').click();assert.equal(await page.locator('#pause').getAttribute('aria-pressed'),'true');await page.locator('#pause').click();assert.equal(await page.locator('#pause').getAttribute('aria-pressed'),'false');});
 await test('Scene menu opens, fits and restores content',async()=>{if(name==='desktop')await page.locator('#menu-toggle').click();else await page.locator('#menu-toggle').tap();await page.waitForTimeout(650);assert(await page.locator('#menu').evaluate(e=>e.open));assert(await page.locator('#content').evaluate(e=>e.inert));await shot('03-menu');await page.keyboard.press('Escape');assert(!(await page.locator('#menu').evaluate(e=>e.open)));assert(!(await page.locator('#content').evaluate(e=>e.inert)));});
 if(name==='mobile')await test('Native touch swipe scrolls instead of being trapped by hero',async()=>{const cdp=await context.newCDPSession(page);const before=await page.evaluate(()=>scrollY);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:190,y:650}]});for(let i=1;i<=12;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:190,y:650-i*20}]});await page.waitForTimeout(20);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(600);assert((await page.evaluate(()=>scrollY))>before+80);});
 await page.locator('#depth-stage').evaluate(e=>e.scrollIntoView({behavior:'instant',block:'center'}));await ready('#depth-stage');await page.waitForTimeout(700);
 await test('Depth image is visible and changes with pointer location',async()=>{const r=await page.locator('#depth-stage').boundingBox();await page.mouse.move(r.x+r.width*.15,r.y+r.height*.25);await page.waitForTimeout(550);const a=await page.locator('#depth-stage').screenshot();await page.mouse.move(r.x+r.width*.85,r.y+r.height*.7);await page.waitForTimeout(550);const b=await page.locator('#depth-stage').screenshot();assert(!a.equals(b));await shot('04-depth');});
 await test('Study opens with history entry and Back restores the page',async()=>{await page.locator('#depth-stage').click();await page.waitForFunction(()=>document.querySelector('#detail').open);assert(new URL(page.url()).hash==='#depth-study');await shot('05-detail');await page.goBack();await page.waitForFunction(()=>!document.querySelector('#detail').open);assert.equal(await page.evaluate(()=>document.body.style.overflow),'');});
 for(const [p,label,phase]of [[0,'06-portal','portal'],[.28,'07-dark','dark tunnel'],[.62,'08-fold','fold'],[.8,'09-bright','light tunnel'],[.95,'10-glass','glass / emergence'],[1,'11-exit','glass / emergence']])await test('Journey renders '+phase+' at '+p,async()=>{await scene(p);assert.equal(await page.evaluate(()=>window.__motionLab.phase),phase);await shot(label);});
 await test('Reverse scrolling restores earlier phase',async()=>{await scene(.32);assert.equal(await page.evaluate(()=>window.__motionLab.phase),'dark tunnel');});
 await test('Scrubber changes actual scroll progress',async()=>{await page.locator('#scrubber').evaluate(e=>{e.value='790';e.dispatchEvent(new Event('input',{bubbles:true}));});await page.waitForTimeout(700);assert(Math.abs((await page.evaluate(()=>window.__motionLab.progress))-.79)<.025);});
 await test('Hold-to-slow releases correctly',async()=>{const r=await page.locator('#slow').boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();assert.equal(await page.locator('#slow').getAttribute('aria-pressed'),'true');await page.waitForTimeout(350);await page.mouse.up();assert.equal(await page.locator('#slow').getAttribute('aria-pressed'),'false');});
 await test('No horizontal document overflow in portrait and landscape',async()=>{assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await page.setViewportSize({width:844,height:390});await page.waitForTimeout(550);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await shot('12-landscape');});
 await test('No captured JavaScript or WebGL shader errors',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(await page.evaluate(()=>window.__motionLab.errors),[]);});
 }catch(e){result.errors.push({engine:name,error:e.message});try{await shot('fatal');}catch{}}
 result.engines.push({name,version:browser.version(),options,consoleErrors:errors});await context.close();await browser.close();
}
const browser=await chromium.launch({args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});const page=await context.newPage();
try{await page.goto('http://127.0.0.1:4173/?no-webgl');await page.waitForFunction(()=>document.querySelector('#hero-stage').classList.contains('error'));assert.equal(await page.locator('#pause').getAttribute('aria-pressed'),'true');await page.locator('#menu-toggle').click();assert(await page.locator('#menu').evaluate(e=>e.open));result.tests.push({engine:'fallback',label:'No-WebGL fallback and reduced-motion controls remain available',status:'passed'});}catch(e){result.tests.push({engine:'fallback',status:'failed',error:e.message});}await browser.close();
result.summary={passed:result.tests.filter(t=>t.status==='passed').length,failed:result.tests.filter(t=>t.status==='failed').length,fatal:result.errors.length};await fs.writeFile('evidence/results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result.summary));if(result.summary.failed||result.summary.fatal)process.exitCode=1;
